/*
 * JScience - Java(TM) Tools and Libraries for the Advancement of Sciences.
 * Copyright (C) 2010 - JScience (http://jscience.org/)
 * All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this software is
 * freely granted, provided that this notice is preserved.
 */
/* Generated By:JavaCC: Do not edit this line. UCUMParserConstants.java */
package org.jscience.physics.internal.unit.format;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface UCUMParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ATOM_CHAR = 1;
  /** RegularExpression Id. */
  int ESCAPED_ATOM_CHAR = 2;
  /** RegularExpression Id. */
  int TERMINAL_ATOM_CHAR = 3;
  /** RegularExpression Id. */
  int LCBRACKET = 4;
  /** RegularExpression Id. */
  int RCBRACKET = 5;
  /** RegularExpression Id. */
  int LSBRACKET = 6;
  /** RegularExpression Id. */
  int RSBRACKET = 7;
  /** RegularExpression Id. */
  int ANNOTATION = 8;
  /** RegularExpression Id. */
  int FACTOR = 9;
  /** RegularExpression Id. */
  int SIGN = 10;
  /** RegularExpression Id. */
  int DOT = 11;
  /** RegularExpression Id. */
  int SOLIDUS = 12;
  /** RegularExpression Id. */
  int ATOM = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ATOM_CHAR>",
    "<ESCAPED_ATOM_CHAR>",
    "<TERMINAL_ATOM_CHAR>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<ANNOTATION>",
    "<FACTOR>",
    "<SIGN>",
    "\".\"",
    "\"/\"",
    "<ATOM>",
    "\"(\"",
    "\")\"",
  };

}
